### ISSUE TITLE
Passing 'this' to the closure

### ISSUE THREAD

**Issue by afhole** [makeable/uuid-v4.js#2]
What is the purpose of passing 'this' to the closure?
The closure takes no arguments, and then just uses whatever 'this' happens to be inside that closure anyway. Am I missing something?

**Comment by makeable** [comment]
No reason, just an overeager editor snippet :)

**Comment by afhole** [comment]
That's what I had thought, but in order to use the 'this' that's passed to the closure you'd have to reference it as an argument. The reference to 'this' inside the function (this.UUID) will just be whatever this is already bound to. Unless I am mistaken, which is entirely possible!

**Comment by makeable** [comment]
No, it looks like you are entirely correct. Its passing in the current context to the closure then completely ignoring it and relying on the leaked scope. Ill get this fixed! Good catch :)

**Comment by makeable** [comment]
https://github.com/makeable/uuid-v4.js/commit/907f7eb0969de53a5bbe46532645994fb521203c

**Comment by afhole** [comment]
Awesome, thanks :)
